### ISSUE TITLE
App Market doesn't work properly on a new version of OpenComputers

### ISSUE THREAD

**Issue by ivan123-tty** [IgorTimofeev/MineOS#547]
When I open App Market, it shows this (or similar) error for less than a second. To see it for much longer, you just navigate to a different tab.
I feel like it has to do with a new OpenComputers update. 
https://github.com/MightyPirates/OpenComputers/releases/tag/1.12.2-forge%2F1.8.0
![javaw_9oLcSsXZQe](https://user-images.githubusercontent.com/70339505/236690148-c51a2050-7aeb-48d5-bf99-222c72d02ca4.png)

**Comment by IgorTimofeev** [comment]
Strange, but should be fixed now, thx!

**Comment by ivan123-tty** [comment]
I still get this error. This time though, App Market crashes.
![image](https://user-images.githubusercontent.com/70339505/236701386-ea6e6002-ebb1-406c-a147-921607f5ead3.png)

**Comment by IgorTimofeev** [comment]
Interesting, seems like content-length header returns some weird data. I'll add extra check for it's sanity, thx

**Comment by ivan123-tty** [comment]
Thanks, this exact error was fixed. However, I encountered a different one when I tried updating MineOS.
![image](https://user-images.githubusercontent.com/70339505/236875200-2427caf2-2302-4e7b-84b3-888e4b847c72.png)

**Comment by ivan123-tty** [comment]
Another weird thing: Seems like I can't even change a page (it keeps showing the same apps)

**Comment by IgorTimofeev** [comment]
> button "update all"). It crashed App Market as well.

I can't fix this. Fuck knows what it depends on and how to reproduce. Just checked updating/pages switching - it work. Sorry, bro

**Comment by ivan123-tty** [comment]
Not sure if it's helpful information, but I confirmed that this issue started in exactly 1.8.0. If I will manage to find more helpful information, I'll let you know.

1.8.0: doesn't work properly
v1.8.0-snapshot-20220917: works
1.7.7: works
1.7.6: works
1.7.5: works

**Comment by IgorTimofeev** [comment]
Thx, but don't worry! It's dead project, if something was broken - ok then xd
